# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# Config version for compatibility and deprecations
config-version = 2

# Especifica los espacios de trabajo que nunca deben cerrarse
persistent-workspaces = ['1', '2', '3', '4', '5', '6', '7']

# Window Rules consolidadas
on-window-detected = [
  { if.app-id = 'com.google.Chrome', run = 'move-node-to-workspace 1' },
  { if.app-name-regex-substring = 'spotify', run = 'move-node-to-workspace 5' },
  { if.app-name-regex-substring = 'Davinci Resolve', run = 'move-node-to-workspace 4' },
  { if.app-id = 'com.mitchellh.ghostty', run = 'move-node-to-workspace 2' },
  { if.app-id = 'md.obsidian', run = 'move-node-to-workspace 2' },
  { if.app-name-regex-substring = 'eseecloud', run = 'layout floating' },
  { if.app-name-regex-substring = 'finder', run = 'layout floating' },
  { if.app-name-regex-substring = 'bitwarden', run = 'layout floating' }
]

after-login-command = []

# Aquí modificamos JankyBorders: 
# active_color = 0xff00ffff (Neón Cian brillante. Los primeros 'ff' son opacidad 100%)
# inactive_color = 0x00000000 (Completamente transparente. Los primeros '00' son opacidad 0%)
after-startup-command = [
  'exec-and-forget borders active_color=0xff00ffff inactive_color=0x00000000 width=4.0'
]

# Start AeroSpace at login
start-at-login = true 

# Normalizations.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Layouts
accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']
# Turn off macOS "Hide application" (cmd-h) feature
automatically-unhide-macos-hidden-apps = true 

# Notify Sketchybar about workspace change and update icons
exec-on-workspace-change = ['/bin/bash', '-c', 'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE && ~/.config/sketchybar/plugins/update_workspace_icons.sh']

# Possible values: (qwerty|dvorak)
[key-mapping]
preset = 'qwerty'

# Espacios eliminados (todos en 0)
[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.bottom = 0
outer.top = 0
outer.right = 0
outer.left = 0

# 'main' binding mode declaration
[mode.main.binding]

# App shortcuts
alt-o = 'exec-and-forget open -a /Applications/Ghostty.app'
alt-s = 'exec-and-forget open -a /Applications/Spotify.app'
alt-v = "exec-and-forget open -a 'Visual Studio Code'"
alt-a = 'exec-and-forget open -a "Google Chrome"'
alt-shift-r = ['exec-and-forget /opt/homebrew/bin/sketchybar --reload']

# Layout
alt-e = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-f = 'fullscreen'
alt-y = ['focus right', 'join-with down', 'layout tiles horizontal']

# Focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'

# Move node to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'

# Workspace back and forth
alt-tab = 'workspace-back-and-forth'
# Move workspace to monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Mode
alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

# force certain workspaces to certain monitors
[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'secondary'
7 = 'secondary'
